[package]

name        = "nix"
description = "Rust friendly bindings to *nix APIs"
version     = "0.3.5"
authors     = ["Carl Lerche <me@carllerche.com>"]
homepage    = "https://github.com/carllerche/nix-rust"
license     = "MIT"
exclude     = [
  ".gitignore",
  ".travis.yml",
  "deploy.sh",
  "test/**/*"
]

[features]

eventfd = []

[dependencies]
libc     = "0.1.4"
bitflags = "0.1.1"

[dev-dependencies]
rand = "0.3.8"

[dev-dependencies.nix-test]
path    = "nix-test"
version = "*"

[[test]]

name = "test"
path = "test/test.rs"
